[colors.bright]
black = "#918175"
blue = "#68a8e4"
cyan = "#53fde9"
green = "#98bc37"
magenta = "#ff5c8f"
red = "#f75341"
white = "#fce8c3"
yellow = "#fed06e"

[colors.cursor]
cursor = "#fbb829"
text = "CellBackground"

[colors.normal]
black = "#1c1b19"
blue = "#2c78bf"
cyan = "#0aaeb3"
green = "#519f50"
magenta = "#e02c6d"
red = "#ef2f27"
white = "#d0bfa1"
yellow = "#fbb829"

[colors.primary]
background = "#1c1b19"
foreground = "#fce8c3"

[font]
size = 11.0

[font.normal]
# to use the BQN font, in the terminal, type
# `alacritty msg config 'font.normal.family="BQN386 Unicode"'`
family = "Hack"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Up"
key = "S"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "T"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "C"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "R"
mode = "Vi|~Search"

[scrolling]
history = 1000
multiplier = 3

[shell]
program = "/usr/bin/zsh"

[window]
startup_mode = "Maximized"
