#!/bin/bash

# configure keyboard mapping
cwd="$(git rev-parse --show-toplevel)"
sudo mkdir -p /etc/X11/xorg.conf.d/
sudo cp $cwd/20-keyboard.conf /etc/X11/xorg.conf.d/20-keyboard.conf

# install vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
