#!/bin/bash

cwd="$(git rev-parse --show-toplevel)"

[ ! -d "~/.config/alacritty" ] && mkdir -p ~/.config/alacritty
[ ! -d "~/.config/ctags" ] && mkdir -p ~/.config/ctags
[ ! -d "~/.config/nvim" ] && mkdir -p ~/.config/nvim
[ ! -d "~/.config/cabal" ] && mkdir -p ~/.config/cabal
[ ! -d "~/.config/rofi" ] && mkdir -p ~/.config/rofi
[ ! -d "~/.config/i3" ] && mkdir -p ~/.config/i3
[ ! -d "~/.config/i3status" ] && mkdir -p ~/.config/i3status
[ ! -d "~/.config/dunst" ] && mkdir -p ~/.config/dunst
[ ! -d "~/.config/redshift" ] && mkdir -p ~/.config/redshift
[ ! -d "~/.config/redshift/hooks" ] && mkdir -p ~/.config/redshift/hooks
[ ! -d "~/.config/picom" ] && mkdir -p ~/.config/picom

ln -sf $cwd/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
ln -sf $cwd/ctags/default.ctags ~/.config/ctags/default.ctags
ln -sf $cwd/git/gitconfig ~/.gitconfig
ln -sf $cwd/git/gitignore ~/.gitignore
ln -sf $cwd/tmux/tmux.conf ~/.tmux.conf
ln -sf $cwd/vim/init.vim ~/.config/nvim/init.vim
ln -sf $cwd/vim/ginit.vim ~/.config/nvim/ginit.vim
ln -sf $cwd/zsh/zshrc ~/.zshrc
ln -sf $cwd/zsh/p10k.zsh ~/.p10k.zsh
ln -sf $cwd/cabal/config ~/.cabal/config
ln -sf $cwd/rofi/config.rasi ~/.config/rofi/config.rasi
ln -sf $cwd/rofi/srcery.rasi ~/.config/rofi/srcery.rasi
ln -sf $cwd/sqlite/sqliterc ~/.sqliterc
ln -sf $cwd/i3/config ~/.config/i3/config
ln -sf $cwd/i3/i3status-config ~/.config/i3status/config
ln -sf $cwd/dunst/dunstrc ~/.config/dunst/dunstrc
ln -sf $cwd/redshift/redshift.conf ~/.config/redshift/redshift.conf
ln -sf $cwd/redshift/hook ~/.config/redshift/hooks/hook
ln -sf $cwd/picom/picom.conf ~/.config/picom/picom.conf
