#!/bin/bash

set -eou pipefail

if ! command -v curlie &>/dev/null
then
    echo "curlie command not found"
    exit
fi

es_url=https://vpc-main-yzg5x33ni4dtuc5wodsezyw4gi.eu-west-1.es.amazonaws.com
file_handle=${1-"es.json"}
es_index=${2-"gensdeconfiance_french_m_2020-05-11-161612"}

cat $file_handle | curlie GET $es_url/$es_index/_search
