#!/bin/bash

set -euo pipefail

if ! command -v mysql &>/dev/null
then
    echo "mysql command not found"
    exit
fi

if [ -z "${1-}" ]
then
    echo "No command supplied"
    exit
fi

env="$1"

if [ "$env" = "local" ]
then
    mysql -h 127.0.0.1 -P 3306 --protocol=tcp -u root -proot -s -B -D gdc -e "$2"
    exit
fi

# STAGING READER
if [ "$env" = "staging" ]
then
    mysql --host=10.66.33.249 --port=3306 --user=gdc_user --password=$(aws ssm get-parameter --profile staging --name /all-applications/DATABASE_DEFAULT_PASSWORD --with-decryption | jq -r '.Parameter.Value') -D gdc_db -e "$2"
    exit
fi

# PREPROD READER
if [ "$env" = "preprod" ]
then
    mysql --host=10.65.41.58 --port=3307 --user=gdc_user --password=$(aws ssm get-parameter --profile preprod --name /all-applications/DATABASE_DEFAULT_PASSWORD --with-decryption | jq -r '.Parameter.Value') -D gdc_db -e "$2"
    exit
fi

if [ "$env" = "prod" ]
then
    mysql --host=10.64.45.16 --port=3307 --user=gdc_user --password=$(aws ssm get-parameter --profile prod --name /all-applications/DATABASE_DEFAULT_PASSWORD --with-decryption | jq -r '.Parameter.Value') -B -D gdc_db -e "$2"
    exit
fi

echo "Unknown env"
