#!/bin/bash

set -euo pipefail

function join_by
{
    local d=${1-} f=${2-}; if shift 2; then printf %s "$f" "${@/#/$d}"; fi;
}

if ! command -v aws &>/dev/null
then
    echo "aws command not found"
    exit
fi

if [ -z "${1-}" ]
then
    echo "No command supplied"
    exit
fi

read -r -a params <<< "$@"
container_command="[\"$(join_by '","' ${params[@]})\"]"

# STAGING
aws ecs run-task \
    --profile staging \
    --region eu-west-1 \
    --cluster arn:aws:ecs:eu-west-1:190654273944:cluster/gdc-queue \
    --task-definition gdc-cron-fargate-hugo \
    --launch-type FARGATE \
    --overrides "{\"containerOverrides\":[{\"name\":\"cron\", \"command\": ${container_command}}]}" \
    --network-configuration '{ "awsvpcConfiguration" : { "subnets" : ["subnet-0cd09ad787629d813", "subnet-0f4e40430e6f16dc0"], "securityGroups" : ["sg-0980d70dd9cda618c"], "assignPublicIp" : "DISABLED"}}' \
    --started-by hugo
