#!/bin/bash

set -euo pipefail

offset="${1-"1"}"

fromDate=$(date -d "-$offset days" --iso-8601)

repos=("GensDeConfiance.fr" "infra" "analytics")


for repo in "${repos[@]}"
do
    firefox "https://github.com/GensDeConfiance/$repo/pulls?q=is%3Apr+is%3Aopen+-is%3Adraft+updated%3A>%3D$fromDate"
done
