#!/bin/bash

set -eou pipefail
#set -o xtrace

if ! command -v jq &>/dev/null
then
    echo "jq command not found"
    exit
fi

if ! command -v gh &>/dev/null
then
    echo "gh command not found"
    exit
fi


get_prs() {
    offset="${1-"1"}"
    fromDate=$(date -d "-$offset days" --iso-8601)

    gh pr list -L 100 --search "is:open -is:draft updated:>=$fromDate" --jq . --json "title,author,headRefName,number"
}

print_pr_title_and_author() {
    pr_json=$(echo $1)
    for pr in $(echo $pr_json | base64 -d | jq '.[] | @base64' -rc)
    do
        echo -n $(echo $pr | base64 --decode | jq -r '.author.login')
        echo -n '/'
        echo $pr | base64 --decode | jq -r '.title'
    done
}

pr_json=$(get_prs "$@" | base64 -w 0)

choice=$(print_pr_title_and_author $pr_json | fzf | cut -d'/' -f2-)
echo $choice
prName=$(echo $pr_json | base64 -d | jq -r --arg CHOICE "$choice" '.[] | select(.title==$CHOICE) | .headRefName')
number=$(echo $pr_json | base64 -d | jq -r --arg CHOICE "$choice" '.[] | select(.title==$CHOICE) | .number')
review $prName $number
