#!/bin/bash

set -eou pipefail

currentBranchName=$(git rev-parse --abbrev-ref HEAD)
mainBranchName=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

git stash push --include-untracked --message "tmp-git-update" # git sts -m "tmp-git-update"
git fetch upstream --prune # git fp upstream
git checkout $mainBranchName # git co dev
git merge upstream/$mainBranchName --no-overwrite-ignore # git merge upstream/dev
git push # git pu
git checkout $currentBranchName # git co old-branch
git stash list | grep "tmp-git-update" && git stash pop
