#!/bin/bash

currentBranchName=$(git rev-parse --abbrev-ref HEAD)
mainBranchName=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
git stash push --include-untracked --message "tmp-git-fix-fork"
git fetch upstream
git checkout $mainBranchName
git reset --hard upstream/$mainBrainName
git push origin $mainBranchName --force
git checkout $currentBranchName
git stash list | grep "tmp-git-fix-fork" && git stash pop
