#!/bin/bash

set -eou pipefail

currentBranchName=$(git rev-parse --abbrev-ref HEAD)
mainBranchName=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

prName=$1
prNumber=$2

git stash -u
git fetch upstream pull/$prNumber/head:$prName
git checkout $prName
#nvim -c "Git diff $mainBranchName...HEAD | only"
git diff $mainBranchName...HEAD

read -p "(A)pprove / Open in (W)eb:" action
case $action in
    A)
        gh pr review $prNumber --approve=true
        ;;
    W)
        gh pr view $prNumber --web=true
        ;;
esac

git checkout $currentBranchName
# for some reason, sometimes there are still files remaining... so we just clean them all
git checkout .
git branch -D $prName
git stash pop
