#!/bin/bash

set -euo pipefail

# If x is the pos of eDP-1, we need to have 2*x + 1920 = 3440. So x = 760
xrandr --output eDP-1 --mode 1920x1200 --pos 760x1440 --primary --output DP-3 --mode 3440x1440 --pos 0x0

