# To append at the end of ~/.bashrc
VISUAL=nvim
EDITOR="$VISUAL"

source /usr/share/fzf/completion.bash
source /usr/share/fzf/key-bindings.bash

alias t='python ~/dev/t/t.py --task-dir ~/tasks --list tasks.txt'
PS1="\[\033[01;33m\][\u@\h\[\033[01;37m\] \W\[\033[01;33m\]]$\[\033[00m\] "
